spring:
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
